export const dataPortfolio = [
	{
		id: 1,
		title: 'voda-bavaria.by',
		link: 'https://voda-bavaria.by/',
		image: '/portfolio/portfolioCard/bavaria/1.webp',
		alt: 'Сайт клиента питьевая вода Бавария, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/bavaria/2.webp',
		alt2: 'Сайт клиента питьевая вода Бавария, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 2,
		title: '',
		link: 'https://smart-um.by/',
		image: '/portfolio/portfolioCard/smart-um/1.webp',
		alt: 'Сайт клиента обучение детей в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/smart-um/2.webp',
		alt2: 'Сайт клиента обучение детей в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 3,
		title: '',
		link: 'https://copyprintservice.by/',
		image: '/portfolio/portfolioCard/copyprintservice/1.webp',
		alt: 'Сайт клиента копицентр в Минске',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/copyprintservice/2.webp',
		alt2: 'Сайт клиента копицентр в Минске',
		w2: 70,
		h2: 132
	},
	{
		id: 4,
		title: '',
		link: 'https://remontmogilev.by/',
		image: '/portfolio/portfolioCard/remontmogilev/1.webp',
		alt: 'Сайт клиента по ремонту и строительству',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/remontmogilev/2.webp',
		alt2: 'Сайт клиента по ремонту и строительству',
		w2: 70,
		h2: 132
	},
	{
		id: 5,
		title: '',
		link: 'https://avto-help.by/',
		image: '/portfolio/portfolioCard/avto-help/1.webp',
		alt: 'Сайт клиента эвакуатор в Могилеве, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/avto-help/2.webp',
		alt2: 'Сайт клиента эвакуатор в Могилеве, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 6,
		title: 'aprostyle.by',
		link: 'https://aprostyle.by/',
		image: '/portfolio/portfolioCard/aprostyle/1.webp',
		alt: 'Сайт клиента по ремонту кожанных салонов',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/aprostyle/2.webp',
		alt2: 'Сайт клиента по ремонту кожанных салонов',
		w2: 70,
		h2: 132
	},
	{
		id: 7,
		title: 'rem-teh.by',
		link: 'https://rem-teh.by/',
		image: '/portfolio/portfolioCard/rem-teh/1.webp',
		alt: 'Сайт клиента по ремонту бытовой техники',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/rem-teh/2.webp',
		alt2: 'Сайт клиента по ремонту бытовой техники',
		w2: 70,
		h2: 132
	},
	{
		id: 8,
		title: '',
		link: 'https://site-mojka.vercel.app/',
		image: '/portfolio/portfolioCard/mojka/1.webp',
		alt: 'Сайт клиента автомойка, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/mojka/2.webp',
		alt2: 'Сайт клиента автомойка, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 9,
		title: 'evakuator.avto-service.by',
		link: 'https://evakuator.avto-service.by/',
		image: '/portfolio/portfolioCard/evakuator.avto-service/1.webp',
		alt: 'Сайт клиента улуги эвакуатора в Минске',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/evakuator.avto-service/2.webp',
		alt2: 'Сайт клиента улуги эвакуатора в Минске',
		w2: 70,
		h2: 132
	},

	{
		id: 10,
		title: 'birdor.by',
		link: 'https://birdor.by/',
		image: '/portfolio/portfolioCard/birdor/1.webp',
		alt: 'Сайт клиента по ремонту дорог',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/birdor/2.webp',
		alt2: 'Сайт клиента по ремонту дорог',
		w2: 70,
		h2: 132
	},
	{
		id: 11,
		title: '',
		link: 'https://otoplenie.vercel.app/',
		image: '/portfolio/portfolioCard/otoplenie/1.webp',
		alt: 'Сайт клиента по отоплению',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/otoplenie/2.webp',
		alt2: 'Сайт клиента по отоплению',
		w2: 70,
		h2: 132
	},
	{
		id: 12,
		title: '',
		link: 'https://excavator-delta.vercel.app/',
		image: '/portfolio/portfolioCard/excavator/1.webp',
		alt: 'Сайт клиента по прокату миниэкскаватора',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/excavator/2.webp',
		alt2: 'Сайт клиента по прокату миниэкскаватора',
		w2: 70,
		h2: 132
	},
	{
		id: 13,
		title: '',
		link: 'https://podklyuch.by/',
		image: '/portfolio/portfolioCard/pod-klyuch/1.webp',
		alt: 'Сайт клиента по ремонту квартир',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/pod-klyuch/2.webp',
		alt2: 'Сайт клиента по ремонту квартир',
		w2: 70,
		h2: 132
	},
	{
		id: 14,
		title: '',
		link: 'https://cafe-theta.vercel.app/',
		image: '/portfolio/portfolioCard/cafe/1.webp',
		alt: 'Сайт клиента общипит',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/cafe/2.webp',
		alt2: 'Сайт клиента общипит',
		w2: 70,
		h2: 132
	},
	{
		id: 15,
		title: '',
		link: 'https://beltrans.vercel.app/',
		image: '/portfolio/portfolioCard/beltrans/1.webp',
		alt: 'Сайт клиента по грузоперевозкам',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/beltrans/2.webp',
		alt2: 'Сайт клиента по грузоперевозкам',
		w2: 70,
		h2: 132
	},
	{
		id: 16,
		title: '',
		link: 'https://him-chistka.vercel.app/',
		image: '/portfolio/portfolioCard/him-chistka/1.webp',
		alt: 'Сайт клиента химчистка мебели',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/him-chistka/2.webp',
		alt2: 'Сайт клиента химчистка мебели',
		w2: 70,
		h2: 132
	},
	{
		id: 17,
		title: '',
		link: 'https://arenda-tehniki-wta6.vercel.app/',
		image: '/portfolio/portfolioCard/arenda-tehniki/1.webp',
		alt: 'Сайт клиента прокат спецтехники',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/arenda-tehniki/2.webp',
		alt2: 'Сайт клиента прокат спецтехники',
		w2: 70,
		h2: 132
	},
	{
		id: 18,
		title: '',
		link: 'https://master-help.by/',
		image: '/portfolio/portfolioCard/plumber/1.webp',
		alt: 'Сайт клиента услуги муж на час',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/plumber/2.webp',
		alt2: 'Сайт клиента услуги сантехника',
		w2: 70,
		h2: 132
	},
	{
		id: 19,
		title: '',
		link: 'https://lily.by/',
		image: '/portfolio/portfolioCard/lily/1.webp',
		alt: 'Сайт клиента мыльные цветы',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/lily/2.webp',
		alt2: 'Сайт клиента мыльные цветы',
		w2: 70,
		h2: 132
	},
	{
		id: 20,
		title: '',
		link: 'https://ecosan.by/',
		image: '/portfolio/portfolioCard/ecosan/1.webp',
		alt: 'Сайт клиента разработка документов по экологии',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/ecosan/2.webp',
		alt2: 'Сайт клиента разработка документов по экологии',
		w2: 70,
		h2: 132
	},
	{
		id: 21,
		title: '',
		link: 'https://metr-evakuator.by/',
		image: '/portfolio/portfolioCard/metr-evakuator/1.webp',
		alt: 'Сайт клиента услуги эвакуатора',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/metr-evakuator/2.webp',
		alt2: 'Сайт клиента услуги эвакуатора',
		w2: 70,
		h2: 132
	},
	{
		id: 22,
		title: '',
		link: 'https://avto-service.by/',
		image: '/portfolio/portfolioCard/avto-service/1.webp',
		alt: 'Сайт клиента СТО',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/avto-service/2.webp',
		alt2: 'Сайт клиента СТО',
		w2: 70,
		h2: 132
	},
	{
		id: 23,
		title: '',
		link: 'https://maria-course.vercel.app/',
		image: '/portfolio/portfolioCard/maria-course/1.webp',
		alt: 'Сайт клиента группа психолога',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/maria-course/2.webp',
		alt2: 'Сайт клиента группа психолога',
		w2: 70,
		h2: 132
	},
	{
		id: 24,
		title: '',
		link: 'https://vi-tech.vercel.app/',
		image: '/portfolio/portfolioCard/vi-tech/1.webp',
		alt: 'Наш первый сайт, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/vi-tech/2.webp',
		alt2: 'Наш первый сайт, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	// {
	// 	id: 21,
	// 	title: '',
	// 	link: 'https://perevozki.minsk.by/',
	// 	image: '/portfolio/portfolioCard/perevozki_bus/1.webp',
	// 	alt: 'Сайт клиента по грузоперевозкам в Минске, компании VI:TECH',
	// 	w: 1000,
	// 	h: 566,
	// 	image2: '/portfolio/portfolioCard/perevozki_bus/2.webp',
	// 	alt2: 'Сайт клиента по грузоперевозкам в Минске, компании VI:TECH',
	// 	w2: 70,
	// 	h2: 132
	// },
	{
		id: 25,
		title: '',
		link: 'https://pasha-front.vercel.app/',
		image: '/portfolio/portfolioCard/pasha/1.webp',
		alt: 'Сайт клиента тестирование it продуктов, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/pasha/2.webp',
		alt2: 'Сайт клиента тестирование it продуктов, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 26,
		title: '',
		link: 'https://movie-html-dusky.vercel.app/',
		image: '/portfolio/portfolioCard/movie/1.webp',
		alt: 'Сайт для портфолио, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/movie/2.webp',
		alt2: 'Сайт для портфолио, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 27,
		title: '',
		link: 'https://victor-irzunov.github.io/',
		image: '/portfolio/portfolioCard/porfolio_my/1.webp',
		alt: 'Сайт портфолио, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/porfolio_my/2.webp',
		alt2: 'Сайт портфолио, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 28,
		title: '',
		link: 'https://victor-irzunov.github.io/irzunovaMariya/',
		image: '/portfolio/portfolioCard/masha/1.webp',
		alt: 'Сайт клиента психолога, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/masha/2.webp',
		alt2: 'Сайт клиента психолога, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 29,
		title: '',
		link: 'https://my-blog-psi-gold.vercel.app/',
		image: '/portfolio/portfolioCard/my_blog/1.webp',
		alt: 'Сайт портфолио 2, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/my_blog/2.webp',
		alt2: 'Сайт портфолио 2, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	// {
	// 	id: 28,
	// 	title: '',
	// 	link: 'https://trans-gruz.by/',
	// 	image: '/portfolio/portfolioCard/trans-gruz/1.webp',
	// 	alt: 'Сайт клиента по грузоперевозкам, компании VI:TECH',
	// 	w: 1000,
	// 	h: 566,
	// 	image2: '/portfolio/portfolioCard/trans-gruz/2.webp',
	// 	alt2: 'Сайт клиента по грузоперевозкам, компании VI:TECH',
	// 	w2: 70,
	// 	h2: 132
	// },
	{
		id: 30,
		title: '',
		link: 'https://avtobiz.by/',
		image: '/portfolio/portfolioCard/avtobiz/1.webp',
		alt: 'Сайт клиента по аренде погрузчика, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/avtobiz/2.webp',
		alt2: 'Сайт клиента по аренде погрузчика, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 31,
		title: '',
		link: 'https://belshow.by/',
		image: '/portfolio/portfolioCard/shou/1.webp',
		alt: 'Сайт клиента искусство шоу Бетельгейз, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/shou/2.webp',
		alt2: 'Сайт клиента искусство шоу Бетельгейз, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 32,
		title: '',
		link: 'https://obuvcomplekt.by/',
		image: '/portfolio/portfolioCard/obuvcomplekt/1.webp',
		alt: 'Сайт клиента магазин искусственной кожи, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/obuvcomplekt/2.webp',
		alt2: 'Сайт клиента магазин искусственной кожи, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 33,
		title: '',
		link: 'https://rezonansgroup.by/',
		image: '/portfolio/portfolioCard/rezonansgroup/1.webp',
		alt: 'Сайт клиента оптовый склад смазочных материалов, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/rezonansgroup/2.webp',
		alt2: 'Сайт клиента оптовый склад смазочных материалов, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 34,
		title: '',
		link: 'https://irzunova.by/',
		image: '/portfolio/portfolioCard/masha-production/1.webp',
		alt: 'Сайт клиента психолог в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/masha-production/2.webp',
		alt2: 'Сайт клиента психолог в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 35,
		title: '',
		link: 'https://speedrepair.by/',
		image: '/portfolio/portfolioCard/STO/1.webp',
		alt: 'Сайт сто в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/STO/2.webp',
		alt2: 'Сайт сто в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 36,
		title: '',
		link: 'https://koronatools.by/',
		image: '/portfolio/portfolioCard/korona/1.webp',
		alt: 'Сайт клиента по продаже минитехники, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/korona/2.webp',
		alt2: 'Сайт клиента по продаже минитехники, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 37,
		title: '',
		link: 'https://klining.vercel.app/',
		image: '/portfolio/portfolioCard/klining/1.webp',
		alt: 'Сайт клиента по услугам клининга, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/klining/2.webp',
		alt2: 'Сайт клиента по услугам клининга, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 38,
		title: '',
		link: 'https://tovarka.vercel.app/',
		image: '/portfolio/portfolioCard/tovarka/1.webp',
		alt: 'Сайт клиента продажа товара, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/tovarka/2.webp',
		alt2: 'Сайт клиента продажа товара, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 39,
		title: '',
		link: 'https://plumber-minsk.vercel.app/',
		image: '/portfolio/portfolioCard/plumber2/1.webp',
		alt: 'Сайт клиента услуги сантехника, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/plumber2/2.webp',
		alt2: 'Сайт клиента услуги сантехника, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 40,
		title: 'dim-master.by',
		link: 'https://dim-master.by/',
		image: '/portfolio/portfolioCard/dim-master/1.webp',
		alt: 'Сайт клиента услуги по установки дверей, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/dim-master/2.webp',
		alt: 'Сайт клиента услуги по установки дверей, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 41,
		title: '',
		link: 'https://remont-minsk.vercel.app/',
		image: '/portfolio/portfolioCard/remont/1.webp',
		alt: 'Сайт клиента ремонт квартир, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/remont/2.webp',
		alt2: 'Сайт клиента ремонт квартир, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 42,
		title: '',
		link: 'https://obuchenie-beta.vercel.app/',
		image: '/portfolio/portfolioCard/obrazovanie/1.webp',
		alt: 'Сайт клиента образователный центр, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/obrazovanie/2.webp',
		alt2: 'Сайт клиента образователный центр, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 43,
		title: '',
		link: 'https://arenda-tehniki.vercel.app/',
		image: '/portfolio/portfolioCard/arenda-teh2/1.webp',
		alt: 'Сайт клиента аренда спецтехники, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/arenda-teh2/2.webp',
		alt2: 'Сайт клиента аренда спецтехники, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 44,
		title: '',
		link: 'https://stroitelstvo.vercel.app/',
		image: '/portfolio/portfolioCard/stroitelstvo/1.webp',
		alt: 'Сайт строительства и ремонта, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/stroitelstvo/2.webp',
		alt2: 'Сайт строительства и ремонта, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 45,
		title: '',
		link: 'https://ukladka-plitki.vercel.app/',
		image: '/portfolio/portfolioCard/plitochnik/1.webp',
		alt: 'Сайт услуги плиточника, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/plitochnik/2.webp',
		alt: 'Сайт услуги плиточника, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 46,
		title: 'prokat-minsk.vercel.app',
		link: 'https://prokat-minsk.vercel.app/',
		image: '/portfolio/portfolioCard/prokatInstrumenta/1.webp',
		alt: 'Сайт клиента Прокат инструмента, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/prokatInstrumenta/2.webp',
		alt: 'Сайт клиента Прокат инструмента, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 47,
		title: 'prokat-minsk.vercel.app',
		link: 'https://yabloki.by/',
		image: '/portfolio/portfolioCard/grodno-yabloki/1.webp',
		alt: 'Сайт клиента Продажа саженцов яблонь, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/grodno-yabloki/2.webp',
		alt: 'Сайт клиента Продажа саженцов яблонь, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 48,
		title: 'it-grodno.vercel.app',
		link: 'https://it-grodno.vercel.app/',
		image: '/portfolio/portfolioCard/mySiteMini/1.webp',
		alt: 'Сайт компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/mySiteMini/2.webp',
		alt: 'Сайт компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 49,
		title: 'car-service-one.vercel.app',
		link: 'https://car-service-one.vercel.app/',
		image: '/portfolio/portfolioCard/car-service2/1.webp',
		alt: 'Сайт клиента СТО, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/car-service2/2.webp',
		alt: 'Сайт клиента СТО, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 50,
		title: 'cleantime.by',
		link: 'https://cleantime.by/',
		image: '/portfolio/portfolioCard/cleantime.by/1.webp',
		alt: 'Сайт клиента услуги Клининга, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/cleantime.by/2.webp',
		alt: 'Сайт клиента услуги Клининга, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 51,
		title: 'demontazh.vercel.app',
		link: 'https://demontazh.vercel.app/',
		image: '/portfolio/portfolioCard/demontazh/1.webp',
		alt: 'Сайт клиента услуги Демонтажа, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/demontazh/2.webp',
		alt: 'Сайт клиента услуги Демонтажа, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 52,
		title: 'pokraska.vercel.app',
		link: 'https://pokraska.vercel.app/',
		image: '/portfolio/portfolioCard/pokraska/1.webp',
		alt: 'Сайт клиента услуги покраски авто, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/pokraska/2.webp',
		alt: 'Сайт клиента услуги покраски авто, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 53,
		title: 'evakuator-snowy.vercel.app',
		link: 'https://evakuator-snowy.vercel.app/',
		image: '/portfolio/portfolioCard/evakuator2/1.webp',
		alt: 'Сайт клиента услуги эвакуатора, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/evakuator2/2.webp',
		alt: 'Сайт клиента услуги эвакуатора, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 54,
		title: 'evakuator-snowy.vercel.app',
		link: 'https://intenso.by/',
		image: '/portfolio/portfolioCard/cofe-intenso/1.webp',
		alt: 'Сайт клиента продажа кофе, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/cofe-intenso/2.webp',
		alt: 'Сайт клиента продажа кофе, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 55,
		title: 'agent-minsk.vercel.app',
		link: 'https://agent-minsk.vercel.app/',
		image: '/portfolio/portfolioCard/realt/1.webp',
		alt: 'Сайт клиента агент по недвижимости, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/realt/2.webp',
		alt: 'Сайт клиента агент по недвижимости, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 56,
		title: 'master-na-chas.vercel.app',
		link: 'https://master-na-chas.vercel.app/',
		image: '/portfolio/portfolioCard/muzh-na-chas/1.webp',
		alt: 'Сайт клиента услуга Муж на час, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/muzh-na-chas/2.webp',
		alt: 'Сайт клиента услуга Муж на час, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 57,
		title: 'pekarnya.vercel.app',
		link: 'https://pekarnya.vercel.app/',
		image: '/portfolio/portfolioCard/pekarnya/1.webp',
		alt: 'Сайт клиента Пекарня в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/pekarnya/2.webp',
		alt: 'Сайт клиента Пекарня в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 58,
		title: 'sportzal.vercel.app/',
		link: 'https://sportzal.vercel.app/',
		image: '/portfolio/portfolioCard/sportzal/1.webp',
		alt: 'Сайт клиента Тренажерный зал в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/sportzal/2.webp',
		alt: 'Сайт клиента Тренажерный зал в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 59,
		title: 'eiw.by',
		link: 'https://eiw.by/',
		image: '/portfolio/portfolioCard/electrik/1.webp',
		alt: 'Сайт клиента Электрик в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/electrik/2.webp',
		alt: 'Сайт клиента Электрик в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 60,
		title: 'bankety.by',
		link: 'https://bankety.by/',
		image: '/portfolio/portfolioCard/bankety.by/1.webp',
		alt: 'Сайт клиента Банкетный зал в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/bankety.by/2.webp',
		alt: 'Сайт клиента Банкетный зал в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 61,
		title: 'cafe-new.vercel.app',
		link: 'https://cafe-new.vercel.app/',
		image: '/portfolio/portfolioCard/cafe-new/1.webp',
		alt: 'Сайт клиента Кафе в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/cafe-new/2.webp',
		alt: 'Сайт клиента Кафе в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 62,
		title: 'english-tutor-minsk.vercel.app',
		link: 'https://english-tutor-minsk.vercel.app/',
		image: '/portfolio/portfolioCard/english/1.webp',
		alt: 'Сайт клиента Репетитор по английскому в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/english/2.webp',
		alt: 'Сайт клиента Репетитор по английскому в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 63,
		title: 'astro-vedic.by',
		link: 'https://astro-vedic.by/',
		image: '/portfolio/portfolioCard/astrolog/1.webp',
		alt: 'Сайт клиента Астролог, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/astrolog/2.webp',
		alt: 'Сайт клиента Астролог, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 64,
		title: 'ampersystem.by/',
		link: 'https://ampersystem.by/',
		image: '/portfolio/portfolioCard/ampersystem/1.webp',
		alt: 'Сайт клиента Монтаж элеткрооборудования, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/ampersystem/2.webp',
		alt: 'Сайт клиента Монтаж элеткрооборудования, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 65,
		title: 'avtohelp24.by',
		link: 'https://avtohelp24.by/',
		image: '/portfolio/portfolioCard/avtohelp24/1.webp',
		alt: 'Сайт клиента Эвакуатор, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/avtohelp24/2.webp',
		alt: 'Сайт клиента Эвакуатор, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 66,
		title: 'perevozki-2024.vercel.app',
		link: 'https://perevozkibus.vercel.app/',
		image: '/portfolio/portfolioCard/perevozki-2024/1.webp',
		alt: 'Сайт клиента Перевозки пассажиров, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/perevozki-2024/2.webp',
		alt: 'Сайт клиента Перевозки пассажиров, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 67,
		title: 'vi-tech.site',
		link: 'https://vi-tech.site/',
		image: '/portfolio/portfolioCard/myBlackSite/1.webp',
		alt: 'Сайт компании по разработке сайтов, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/myBlackSite/2.webp',
		alt: 'Сайт компании по разработке сайтов, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 67,
		title: 'car-service2024.vercel.app',
		link: 'https://car-service2024.vercel.app/',
		image: '/portfolio/portfolioCard/car-service_2/1.webp',
		alt: 'Сайт СТО компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/car-service_2/2.webp',
		alt: 'Сайт СТО, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 68,
		title: 'okna-dveri.vercel.app',
		link: 'https://okna-dveri.vercel.app/',
		image: '/portfolio/portfolioCard/okna-dveri/1.webp',
		alt: 'Сайт клиента Окна и Двери ПВХ компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/okna-dveri/2.webp',
		alt: 'Сайт клиента Окна и Двери ПВХ, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 69,
		title: '3310.by',
		link: 'https://3310.by/',
		image: '/portfolio/portfolioCard/3310/1.webp',
		alt: 'Сайт клиента Ремонт телефонов и компьютеров компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/3310/2.webp',
		alt: 'Сайт клиента Ремонт телефонов и компьютеров, компании VI:TECH',
		w2: 70,
		h2: 132
	},
]