export const dataPortfolio = [
	{
		id: 1,
		title: 'aprostyle.by',
		link: 'https://aprostyle.by/',
		image: '/portfolio/portfolioCard/aprostyle/1.webp',
		alt: 'Сайт клиента по ремонту кожанных салонов',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/aprostyle/2.webp',
		alt2: 'Сайт клиента по ремонту кожанных салонов',
		w2: 70,
		h2: 132

	},
	{
		id: 2,
		title: 'rem-teh.by',
		link: 'https://rem-teh.by/',
		image: '/portfolio/portfolioCard/rem-teh/1.webp',
		alt: 'Сайт клиента по ремонту бытовой техники',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/rem-teh/2.webp',
		alt2: 'Сайт клиента по ремонту бытовой техники',
		w2: 70,
		h2: 132

	},
	{
		id: 3,
		title: 'birdor.by',
		link: 'https://birdor.by/',
		image: '/portfolio/portfolioCard/birdor/1.webp',
		alt: 'Сайт клиента по ремонту дорог',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/birdor/2.webp',
		alt2: 'Сайт клиента по ремонту дорог',
		w2: 70,
		h2: 132

	},
	{
		id: 4,
		title: '',
		link: 'https://otoplenie.vercel.app/',
		image: '/portfolio/portfolioCard/otoplenie/1.webp',
		alt: 'Сайт клиента по отоплению',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/otoplenie/2.webp',
		alt2: 'Сайт клиента по отоплению',
		w2: 70,
		h2: 132
	},
	{
		id: 5,
		title: '',
		link: 'https://excavator-delta.vercel.app/',
		image: '/portfolio/portfolioCard/excavator/1.webp',
		alt: 'Сайт клиента по прокату миниэкскаватора',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/excavator/2.webp',
		alt2: 'Сайт клиента по прокату миниэкскаватора',
		w2: 70,
		h2: 132
	},
	{
		id: 6,
		title: '',
		link: 'https://pod-klyuch.vercel.app/',
		image: '/portfolio/portfolioCard/pod-klyuch/1.webp',
		alt: 'Сайт клиента по ремонту квартир',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/pod-klyuch/2.webp',
		alt2: 'Сайт клиента по ремонту квартир',
		w2: 70,
		h2: 132
	},
	{
		id: 7,
		title: '',
		link: 'https://cafe-theta.vercel.app/',
		image: '/portfolio/portfolioCard/cafe/1.webp',
		alt: 'Сайт клиента общипит',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/cafe/2.webp',
		alt2: 'Сайт клиента общипит',
		w2: 70,
		h2: 132
	},
	{
		id: 8,
		title: '',
		link: 'https://beltrans.vercel.app/',
		image: '/portfolio/portfolioCard/beltrans/1.webp',
		alt: 'Сайт клиента по грузоперевозкам',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/beltrans/2.webp',
		alt2: 'Сайт клиента по грузоперевозкам',
		w2: 70,
		h2: 132
	},
	{
		id: 9,
		title: '',
		link: 'https://him-chistka.vercel.app/',
		image: '/portfolio/portfolioCard/him-chistka/1.webp',
		alt: 'Сайт клиента химчистка мебели',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/him-chistka/2.webp',
		alt2: 'Сайт клиента химчистка мебели',
		w2: 70,
		h2: 132
	},
	{
		id: 10,
		title: '',
		link: 'https://arenda-tehniki.vercel.app/',
		image: '/portfolio/portfolioCard/arenda-tehniki/1.webp',
		alt: 'Сайт клиента прокат спецтехники',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/arenda-tehniki/2.webp',
		alt2: 'Сайт клиента прокат спецтехники',
		w2: 70,
		h2: 132
	},
	{
		id: 11,
		title: '',
		link: 'https://master-help.by/',
		image: '/portfolio/portfolioCard/plumber/1.webp',
		alt: 'Сайт клиента услуги муж на час',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/plumber/2.webp',
		alt2: 'Сайт клиента услуги сантехника',
		w2: 70,
		h2: 132
	},
	{
		id: 12,
		title: '',
		link: 'https://lily.by/',
		image: '/portfolio/portfolioCard/lily/1.webp',
		alt: 'Сайт клиента мыльные цветы',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/lily/2.webp',
		alt2: 'Сайт клиента мыльные цветы',
		w2: 70,
		h2: 132
	},
	{
		id: 13,
		title: '',
		link: 'https://ecosan.by/',
		image: '/portfolio/portfolioCard/ecosan/1.webp',
		alt: 'Сайт клиента разработка документов по экологии',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/ecosan/2.webp',
		alt2: 'Сайт клиента разработка документов по экологии',
		w2: 70,
		h2: 132
	},
	{
		id: 14,
		title: '',
		link: 'https://metr-evakuator.by/',
		image: '/portfolio/portfolioCard/metr-evakuator/1.webp',
		alt: 'Сайт клиента услуги эвакуатора',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/metr-evakuator/2.webp',
		alt2: 'Сайт клиента услуги эвакуатора',
		w2: 70,
		h2: 132
	},
	{
		id: 15,
		title: '',
		link: 'https://avto-service.by/',
		image: '/portfolio/portfolioCard/avto-service/1.webp',
		alt: 'Сайт клиента СТО',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/avto-service/2.webp',
		alt2: 'Сайт клиента СТО',
		w2: 70,
		h2: 132
	},
	{
		id: 16,
		title: '',
		link: 'https://evakuator.avto-service.by/',
		image: '/portfolio/portfolioCard/evakuator.avto-service/1.webp',
		alt: 'Сайт клиента улуги эвакуатора в Минске',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/evakuator.avto-service/2.webp',
		alt2: 'Сайт клиента улуги эвакуатора в Минске',
		w2: 70,
		h2: 132
	},
	{
		id: 17,
		title: '',
		link: 'https://copyprintservice.by/',
		image: '/portfolio/portfolioCard/copyprintservice/1.webp',
		alt: 'Сайт клиента копицентр в Минске',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/copyprintservice/2.webp',
		alt2: 'Сайт клиента копицентр в Минске',
		w2: 70,
		h2: 132
	},
	{
		id: 18,
		title: '',
		link: 'https://remontmogilev.by/',
		image: '/portfolio/portfolioCard/remontmogilev/1.webp',
		alt: 'Сайт клиента по ремонту и строительству',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/remontmogilev/2.webp',
		alt2: 'Сайт клиента по ремонту и строительству',
		w2: 70,
		h2: 132
	},
	{
		id: 19,
		title: '',
		link: 'https://maria-course.vercel.app/',
		image: '/portfolio/portfolioCard/maria-course/1.webp',
		alt: 'Сайт клиента группа психолога',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/maria-course/2.webp',
		alt2: 'Сайт клиента группа психолога',
		w2: 70,
		h2: 132
	},
	{
		id: 20,
		title: '',
		link: 'https://vi-tech.vercel.app/',
		image: '/portfolio/portfolioCard/vi-tech/1.webp',
		alt: 'Наш первый сайт, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/vi-tech/2.webp',
		alt2: 'Наш первый сайт, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 21,
		title: '',
		link: 'https://perevozki.minsk.by/',
		image: '/portfolio/portfolioCard/perevozki_bus/1.webp',
		alt: 'Сайт клиента по грузоперевозкам в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/perevozki_bus/2.webp',
		alt2: 'Сайт клиента по грузоперевозкам в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 22,
		title: '',
		link: 'https://pasha-front.vercel.app/',
		image: '/portfolio/portfolioCard/pasha/1.webp',
		alt: 'Сайт клиента тестирование it продуктов, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/pasha/2.webp',
		alt2: 'Сайт клиента тестирование it продуктов, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 23,
		title: '',
		link: 'https://movie-html-dusky.vercel.app/',
		image: '/portfolio/portfolioCard/movie/1.webp',
		alt: 'Сайт для портфолио, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/movie/2.webp',
		alt2: 'Сайт для портфолио, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 24,
		title: '',
		link: 'https://victor-irzunov.github.io/',
		image: '/portfolio/portfolioCard/porfolio_my/1.webp',
		alt: 'Сайт портфолио, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/porfolio_my/2.webp',
		alt2: 'Сайт портфолио, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 25,
		title: '',
		link: 'https://victor-irzunov.github.io/irzunovaMariya/',
		image: '/portfolio/portfolioCard/masha/1.webp',
		alt: 'Сайт клиента психолога, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/masha/2.webp',
		alt2: 'Сайт клиента психолога, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 27,
		title: '',
		link: 'https://my-blog-psi-gold.vercel.app/',
		image: '/portfolio/portfolioCard/my_blog/1.webp',
		alt: 'Сайт портфолио 2, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/my_blog/2.webp',
		alt2: 'Сайт портфолио 2, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 28,
		title: '',
		link: 'https://trans-gruz.by/',
		image: '/portfolio/portfolioCard/trans-gruz/1.webp',
		alt: 'Сайт клиента по грузоперевозкам, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/trans-gruz/2.webp',
		alt2: 'Сайт клиента по грузоперевозкам, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 29,
		title: '',
		link: 'https://avtobiz.by/',
		image: '/portfolio/portfolioCard/avtobiz/1.webp',
		alt: 'Сайт клиента по аренде погрузчика, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/avtobiz/2.webp',
		alt2: 'Сайт клиента по аренде погрузчика, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 30,
		title: '',
		link: 'https://belshow.by/',
		image: '/portfolio/portfolioCard/shou/1.webp',
		alt: 'Сайт клиента искусство шоу Бетельгейз, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/shou/2.webp',
		alt2: 'Сайт клиента искусство шоу Бетельгейз, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 31,
		title: '',
		link: 'https://obuvcomplekt.by/',
		image: '/portfolio/portfolioCard/obuvcomplekt/1.webp',
		alt: 'Сайт клиента магазин искусственной кожи, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/obuvcomplekt/2.webp',
		alt2: 'Сайт клиента магазин искусственной кожи, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 32,
		title: '',
		link: 'https://rezonansgroup.by/',
		image: '/portfolio/portfolioCard/rezonansgroup/1.webp',
		alt: 'Сайт клиента оптовый склад смазочных материалов, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/rezonansgroup/2.webp',
		alt2: 'Сайт клиента оптовый склад смазочных материалов, компании VI:TECH',
		w2: 70,
		h2: 132
	},
	{
		id: 33,
		title: '',
		link: 'https://irzunova.by/',
		image: '/portfolio/portfolioCard/masha-production/1.webp',
		alt: 'Сайт клиента психолог в Минске, компании VI:TECH',
		w: 1000,
		h: 566,
		image2: '/portfolio/portfolioCard/masha-production/2.webp',
		alt2: 'Сайт клиента психолог в Минске, компании VI:TECH',
		w2: 70,
		h2: 132
	},
]